version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver ${API_IP}:${API_PORT}
    volumes:
      - ./:/usr/src
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:${PG_VERSION}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_HOST}

volumes:
  postgres_data: