# Generated by Django 4.1.5 on 2023-01-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_item', '0001_initial'),
        ('creative', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creative',
            name='line_items',
        ),
        migrations.AddField(
            model_name='creative',
            name='line_items',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='line_item.lineitem'),
            preserve_default=False,
        ),
    ]
